# This pipeline executes all pre-commit checks and therefore only fails if a contributor does not 
# have pre-commit installed.
name: ensure-pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: |
          python -m pip install poetry
      - name: Install dependencies
        run: |
          poetry config --local virtualenvs.create false
          poetry install
      - name: Install pre-commit
        run: |
          pip install pre-commit
      - name: Run pre-commit checks
        run: pre-commit run --all-files